import { normalizeValue } from '../../core/timeline/timeline';
import { convertDisplayUnit, preferredDisplayUnit, resolveDisplayUnit } from '../../core/units/displayUnit';
import type { ClipComparisonToExtension, ClipComparisonToWebview, ComparisonClipDto } from '../../extension/clips/clipComparisonProtocol';
import type { ChartAxisRangeSetting } from '../../extension/editors/rawLogProtocol';
import { layoutHoverLabelBoxes, layoutTimestampMarker, type HoverLabelRect } from '../shared/chartHoverLabels';
import { arrangeChartGroups, findGraphIndexBySignals, moveChartGroup, moveChartGroupToNewGraph } from '../shared/chartLayout';
import { crossesSeriesGap, displaySeriesRange, renderedSeriesValueAt } from '../shared/chartSeries';
import { chartWheelGesture } from '../shared/chartWheel';
import { t } from '../shared/i18n';
import { SIGNAL_COLOR_PRESETS, SignalSelector } from '../shared/signalSelector';

declare function acquireVsCodeApi(): { postMessage(message: ClipComparisonToExtension): void };

interface Marker { readonly id: string; readonly relativeTimestamp: number; readonly signalIds: readonly string[]; }
interface CanvasHoverValue { readonly y: number; readonly text: string; readonly color: string; }
interface CanvasTimestampMarker { readonly text: string; readonly rect: HoverLabelRect; }
interface TimeRange { readonly start: number; readonly end: number; }
type ComparisonEntry = { readonly clip: ComparisonClipDto; readonly clipIndex: number; readonly series: ComparisonClipDto['series'][number] };
type ComparisonGroup = { readonly key: string; readonly label: string; readonly displayUnit?: string; readonly entries: readonly ComparisonEntry[] };
type ComparisonGraph = readonly ComparisonGroup[];

const vscode = acquireVsCodeApi();
const app = document.getElementById('app')!;
const dashPatterns: readonly number[][] = [[], [8, 4], [2, 3], [10, 3, 2, 3]];
const GRAPH_HEIGHT = 320;
const selected = new Set<string>();
const colors = new Map<string, string>();
const visibleClips = new Set<string>();
const markers = new Map<string, Marker>();
let axisRange: ChartAxisRangeSetting = { mode: 'visible' };
let clips: ComparisonClipDto[] = [];
let normalized = false;
let connectGaps = true;
let groupLayout: string[][] | undefined;
let layoutEditorOpen = false;
let draggedGroupKey: string | undefined;
let requestId = 0;
let latestSeriesRequest = 0;
let hoverRelativeTimestamp: number | undefined;
let hoverGraphIndex: number | undefined;
let hoverScale: { readonly xMin: number; readonly xMax: number; readonly left: number; readonly width: number; readonly graphCount: number } | undefined;
let markerCounter = 0;
let legendHeights: readonly number[] = [];
let interactionDrawScheduled = false;
let fullRange: TimeRange | undefined;
let viewRange: TimeRange | undefined;
let viewportTimer: number | undefined;

app.innerHTML = `
<style>
  *{box-sizing:border-box}body{margin:0;color:var(--vscode-foreground);background:var(--vscode-editor-background);font-family:var(--vscode-font-family)}
  #app{height:100vh;display:flex;flex-direction:column;min-width:0}button,input,select{font:inherit;color:inherit;background:var(--vscode-button-secondaryBackground);border:1px solid var(--vscode-button-border,transparent);border-radius:3px;padding:5px 8px}button{cursor:pointer}button:disabled{opacity:.55;cursor:default}.primary{background:var(--vscode-button-background);color:var(--vscode-button-foreground)}.spacer{flex:1}.muted{color:var(--vscode-descriptionForeground);font-size:12px}
  .toolbar{display:flex;gap:7px;align-items:center;padding:7px 9px;border-bottom:1px solid var(--vscode-panel-border);flex-wrap:wrap}.segmented{display:flex}.segmented button{border-radius:0}.segmented button:first-child{border-radius:3px 0 0 3px}.segmented button:last-child{border-radius:0 3px 3px 0}.clips{max-height:180px;overflow:auto;border-bottom:1px solid var(--vscode-panel-border)}.loading{padding:10px}.clip{display:grid;grid-template-columns:24px minmax(130px,1fr) auto auto auto;gap:6px;align-items:center;padding:5px 9px;border-bottom:1px solid color-mix(in srgb,var(--vscode-panel-border) 45%,transparent)}.clip strong,.clip small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.clip small{color:var(--vscode-descriptionForeground)}.clip output{min-width:120px;font:12px var(--vscode-editor-font-family)}
  .comparison-layout{display:flex;flex:1;min-height:0;min-width:0}.signal-pane{width:260px;flex:0 0 260px;overflow:auto;border-right:1px solid var(--vscode-panel-border);background:var(--vscode-sideBar-background,var(--vscode-editor-background))}.graph-main{display:flex;flex:1;min-width:0;min-height:0;flex-direction:column}.chart-option{display:flex;align-items:center;gap:5px;white-space:nowrap;font-size:12px}.chart-option input{margin:0}.axis-global{display:flex;align-items:center;gap:7px}.axis-global[hidden]{display:none}.axis-mode{display:flex;align-items:center;gap:5px;white-space:nowrap;font-size:12px}.axis-mode select{padding:3px 6px}.chart-navigation{padding-block:5px}.view-range{font-family:var(--vscode-editor-font-family)}.canvas-wrap{position:relative;flex:1;min-height:300px;overflow:auto}canvas{display:block}.markers{position:absolute;left:0;top:0;pointer-events:none}
  .legend{position:absolute;left:0;top:0;z-index:3;width:100%;pointer-events:none;font-size:12px}.legend:empty{display:none}.legend-group{position:absolute;left:0;width:100%;display:flex;align-items:flex-start;gap:10px;min-width:0;padding:5px 9px;background:var(--vscode-editor-background);border-bottom:1px solid color-mix(in srgb,var(--vscode-panel-border) 55%,transparent);pointer-events:auto}.legend-title{flex:0 0 auto;min-width:58px;padding-top:4px;color:var(--vscode-descriptionForeground);font-weight:600}.legend-items{display:flex;align-items:center;gap:8px 10px;flex:1;flex-wrap:wrap;min-width:0}.legend-entry{display:flex;flex:0 0 auto;align-items:center;gap:5px;max-width:100%;white-space:nowrap}.legend-entry i{width:16px;height:0;flex:0 0 auto;border-top:3px solid}.legend-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.axis-badge{min-width:14px;color:var(--vscode-descriptionForeground);font:600 10px var(--vscode-editor-font-family)}
  .layout-editor{border-bottom:1px solid var(--vscode-panel-border);padding:8px 10px;background:var(--vscode-sideBar-background,var(--vscode-editor-background))}.layout-editor[hidden]{display:none}.layout-editor-head{display:flex;gap:8px;align-items:center;margin-bottom:8px}.layout-cards{display:flex;gap:8px;align-items:stretch;overflow-x:auto;padding-bottom:3px}.layout-card{min-width:210px;padding:7px;border:1px solid var(--vscode-panel-border);border-radius:4px}.layout-slots{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:6px}.layout-slot{min-height:48px;padding:5px;border:1px dashed var(--vscode-panel-border);border-radius:3px}.layout-axis{display:block;margin-bottom:3px;color:var(--vscode-descriptionForeground);font:600 10px var(--vscode-editor-font-family)}.layout-chip{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:5px;align-items:center;padding:5px;background:var(--vscode-list-hoverBackground);border:1px solid var(--vscode-panel-border);border-radius:3px;cursor:grab}.layout-chip span:nth-child(2){overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.layout-chip small{color:var(--vscode-descriptionForeground)}.layout-empty{color:var(--vscode-descriptionForeground);font-size:11px}.layout-new{display:flex;min-width:190px;align-items:center;justify-content:center;padding:10px;border:1px dashed var(--vscode-panel-border);border-radius:4px;color:var(--vscode-descriptionForeground)}.drop-target{border-color:var(--vscode-focusBorder);background:color-mix(in srgb,var(--vscode-focusBorder) 12%,transparent)}.dragging{opacity:.45}
  .signal-selector{padding:8px;overflow-anchor:none}.signal-selector>input{width:100%;background:var(--vscode-input-background)}.selector-actions{display:flex;gap:5px;margin:7px 0}.selector-actions button{flex:1}.selector-group{margin-top:5px}.selector-group-head{display:grid;grid-template-columns:24px 20px minmax(0,1fr);align-items:center;min-height:28px;font-weight:600}.selector-group-head>span,.selector-signal>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.selector-expand{padding:1px;background:transparent;border:0}.selector-signal{position:relative;display:grid;grid-template-columns:20px minmax(0,1fr) 22px;align-items:center;min-height:27px;padding-left:24px;font-size:12px}.color-button{width:18px;height:18px;padding:0;border:1px solid var(--vscode-panel-border);border-radius:3px;box-shadow:inset 0 0 0 1px #0002}.color-popup{position:fixed;z-index:30;display:grid;grid-template-columns:repeat(4,24px);gap:5px;padding:7px;border:1px solid var(--vscode-panel-border);border-radius:5px;background:var(--vscode-editor-background);box-shadow:0 3px 12px #0006}.color-swatch{width:24px;height:24px;padding:0;border:2px solid transparent;border-radius:4px;box-shadow:inset 0 0 0 1px #0004}.color-swatch.selected{border-color:var(--vscode-focusBorder);outline:1px solid var(--vscode-focusBorder);outline-offset:1px}
</style>
<div class="toolbar"><strong>${t('Clip Comparison', 'クリップ比較')}</strong><button class="actual primary">${t('Actual (converted units)', '実値（単位換算）')}</button><button class="normalized">${t('Normalized 0–100%', '正規化 0–100%')}</button><label class="chart-option"><input class="connect-gaps" type="checkbox" checked>${t('Connect gaps', '欠損を補完')}</label><span class="axis-global"><label class="axis-mode">${t('Y axis', 'Y軸')}<select class="axis-range-mode" aria-label="${t('Y-axis range for all graphs', '全グラフのY軸範囲')}"><option value="visible">${t('Visible interval', '表示区間')}</option><option value="global">${t('All data', '全データ')}</option></select></label><label class="chart-option"><input class="axis-include-zero" type="checkbox">${t('Include 0', '0を含める')}</label></span><button class="layout-toggle" aria-expanded="false">${t('Graph Layout…', 'グラフ構成…')}</button><button class="save-image">${t('Save Image…', '画像を保存…')}</button><button class="marker-clear" disabled>${t('Clear Markers', 'マーカーを全解除')}</button><span class="spacer"></span><span class="muted">${t('Click the graph to add markers.', 'グラフをクリックしてマーカーを追加')}</span></div>
<div class="clips"><div class="loading muted">${t('Loading Clips…', 'クリップを読み込み中…')}</div></div>
<div class="comparison-layout"><aside class="signal-pane"><div class="signal-selector"></div></aside><section class="graph-main"><div class="toolbar"><strong>${t('Signals', 'Signal')}</strong><span class="selection-status muted">${t('Loading Signals…', 'Signalを読み込み中…')}</span></div><div class="toolbar chart-navigation"><div class="segmented"><button class="pan-left">←</button><button class="zoom-out">−</button><button class="zoom-in">＋</button><button class="pan-right">→</button></div><button class="zoom-reset" disabled>${t('Reset Zoom', 'ズームをリセット')}</button><span class="view-range muted"></span></div><section class="layout-editor" hidden><div class="layout-editor-head"><strong>${t('Graph Layout', 'グラフ構成')}</strong><span class="muted">${t('Drag each unit system to a left or right axis.', '各単位系統を左右の軸へドラッグ')}</span><span class="spacer"></span><button class="layout-auto">${t('Automatic Layout', '自動配置')}</button></div><div class="layout-cards"></div></section><div class="canvas-wrap"><canvas aria-label="${t('Clip comparison graph. Click to add a marker.', 'クリップ比較グラフ。クリックでマーカーを追加。')}"></canvas><div class="legend"></div><div class="markers"></div></div></section></div>`;

const canvas = app.querySelector('canvas')!;
const markerClear = app.querySelector('.marker-clear') as HTMLButtonElement;
const saveImageButton = app.querySelector('.save-image') as HTMLButtonElement;
const selector = new SignalSelector({ host: app.querySelector('.signal-selector')!, selected, colors, onSelectionChange: () => requestSeries(), onColorChange: () => draw() });

app.querySelector('.actual')!.addEventListener('click', () => { normalized = false; updateModeButtons(); draw(); });
app.querySelector('.normalized')!.addEventListener('click', () => { normalized = true; updateModeButtons(); draw(); });
app.querySelector('.connect-gaps')!.addEventListener('change', (event) => { connectGaps = (event.currentTarget as HTMLInputElement).checked; draw(); });
app.querySelector('.axis-range-mode')!.addEventListener('change', (event) => { axisRange = { ...axisRange, mode: (event.currentTarget as HTMLSelectElement).value as 'visible' | 'global' }; draw(); });
app.querySelector('.axis-include-zero')!.addEventListener('change', (event) => { axisRange = { ...axisRange, includeZero: (event.currentTarget as HTMLInputElement).checked }; draw(); });
app.querySelector('.layout-toggle')!.addEventListener('click', () => { layoutEditorOpen = !layoutEditorOpen; updateModeButtons(); renderLayoutEditor(); });
app.querySelector('.layout-auto')!.addEventListener('click', () => { groupLayout = undefined; draw(); });
app.querySelector('.zoom-in')!.addEventListener('click', () => zoom(1 / 1.5)); app.querySelector('.zoom-out')!.addEventListener('click', () => zoom(1.5));
app.querySelector('.pan-left')!.addEventListener('click', () => pan(-1)); app.querySelector('.pan-right')!.addEventListener('click', () => pan(1));
app.querySelector('.zoom-reset')!.addEventListener('click', () => { viewRange = fullRange ? { ...fullRange } : undefined; draw(); }); saveImageButton.addEventListener('click', saveImage);
new ResizeObserver(() => draw()).observe(app.querySelector('.canvas-wrap')!); canvas.addEventListener('wheel', handleWheel, { passive: false }); canvas.addEventListener('mousemove', hover); canvas.addEventListener('mouseleave', () => clearHover()); canvas.addEventListener('click', addMarker); markerClear.addEventListener('click', () => { markers.clear(); updateMarkerControls(); draw(false); });
for (const [query, label] of [['.zoom-in', t('Zoom in', '拡大')], ['.zoom-out', t('Zoom out', '縮小')], ['.pan-left', t('Move view left', '表示を左へ移動')], ['.pan-right', t('Move view right', '表示を右へ移動')]] as const) { const control = app.querySelector(query)!; control.setAttribute('title', label); control.setAttribute('aria-label', label); }
saveImageButton.title = t('Save a screen-size-independent PNG including every graph, legend, range and marker', '全グラフ・凡例・表示範囲・マーカーを含む画面サイズ非依存のPNGを保存');

function requestSeries(): void { clearHover(false); clips = clips.map((clip) => ({ ...clip, series: [] })); fullRange = undefined; viewRange = undefined; latestSeriesRequest = ++requestId; updateSelectionStatus(true); draw(); vscode.postMessage({ type: 'selectSignals', requestId: latestSeriesRequest, signalIds: [...selected] }); }
function updateSelectionStatus(loading = false): void { app.querySelector('.selection-status')!.textContent = loading ? t('Loading selected Signals…', '選択したSignalを読み込み中…') : `${selected.size} ${t('selected', '選択中')}`; }
function updateModeButtons(): void { app.querySelector('.actual')!.classList.toggle('primary', !normalized); app.querySelector('.normalized')!.classList.toggle('primary', normalized); app.querySelector<HTMLElement>('.axis-global')!.hidden = normalized; const toggle = app.querySelector<HTMLButtonElement>('.layout-toggle')!; toggle.disabled = normalized; toggle.classList.toggle('primary', layoutEditorOpen && !normalized); toggle.setAttribute('aria-expanded', String(layoutEditorOpen && !normalized)); app.querySelector<HTMLElement>('.layout-editor')!.hidden = normalized || !layoutEditorOpen; }

function renderClips(): void {
  const host = app.querySelector('.clips')!; host.replaceChildren();
  clips.forEach((clip) => { const row = document.createElement('div'); row.className = 'clip'; const check = document.createElement('input'); check.type = 'checkbox'; check.checked = visibleClips.has(clip.id); check.addEventListener('change', () => { check.checked ? visibleClips.add(clip.id) : visibleClips.delete(clip.id); clearHover(false); draw(); }); const label = document.createElement('span'); label.innerHTML = '<strong></strong><small></small>'; label.querySelector('strong')!.textContent = clip.name; label.querySelector('small')!.textContent = clip.fileName; const previous = button('◀', () => vscode.postMessage({ type: 'shiftAnchor', clipId: clip.id, direction: -1 })); previous.title = t('Align to previous CAN Timestamp', '前のCANタイムスタンプへ位置合わせ'); previous.setAttribute('aria-label', previous.title); const output = document.createElement('output'); output.textContent = offsetText(clip); output.title = t('Click to reset alignment', 'クリックして位置合わせをリセット'); output.style.cursor = 'pointer'; output.addEventListener('click', () => vscode.postMessage({ type: 'resetAnchor', clipId: clip.id })); const next = button('▶', () => vscode.postMessage({ type: 'shiftAnchor', clipId: clip.id, direction: 1 })); next.title = t('Align to next CAN Timestamp', '次のCANタイムスタンプへ位置合わせ'); next.setAttribute('aria-label', next.title); row.append(check, label, previous, output, next); host.appendChild(row); });
}
function button(label: string, click: () => void): HTMLButtonElement { const value = document.createElement('button'); value.textContent = label; value.addEventListener('click', click); return value; }
function offsetText(clip: ComparisonClipDto): string { const offset = clip.anchorTimestamp - clip.startTimestamp; return `${offset >= 0 ? '+' : ''}${format(offset)} s`; }
function comparisonGraphs(groups: readonly ComparisonGroup[]): readonly ComparisonGraph[] { return normalized ? (groups.length ? [groups] : []) : arrangeChartGroups(groups, groupLayout); }

function renderLayoutEditor(): void {
  const cards = app.querySelector<HTMLElement>('.layout-cards')!; cards.replaceChildren(); if (normalized || !layoutEditorOpen) return; const graphs = comparisonGraphs(comparisonGroups(comparisonEntries()));
  if (!graphs.length) { const empty = document.createElement('span'); empty.className = 'muted'; empty.textContent = t('Select Signals to configure the graph layout.', 'Signalを選択するとグラフ構成を設定できます。'); cards.appendChild(empty); return; }
  graphs.forEach((graph, graphIndex) => { const card = document.createElement('section'); card.className = 'layout-card'; const title = document.createElement('strong'); title.textContent = `${t('Graph', 'グラフ')} ${graphIndex + 1}`; card.appendChild(title); const slots = document.createElement('div'); slots.className = 'layout-slots'; ([0, 1] as const).forEach((axisIndex) => { const group = graph[axisIndex]; const slot = document.createElement('div'); slot.className = 'layout-slot'; const axis = document.createElement('span'); axis.className = 'layout-axis'; axis.textContent = axisIndex === 0 ? 'L' : 'R'; slot.appendChild(axis); enableLayoutDrop(slot, graphIndex, axisIndex); if (group) { const chip = document.createElement('div'); chip.className = 'layout-chip'; chip.draggable = true; const handle = document.createElement('span'); handle.textContent = '⠿'; handle.setAttribute('aria-hidden', 'true'); const label = document.createElement('span'); label.textContent = group.label; const count = document.createElement('small'); count.textContent = String(new Set(group.entries.map((entry) => entry.series.definition.id)).size); chip.append(handle, label, count); chip.addEventListener('dragstart', (event) => { draggedGroupKey = group.key; event.dataTransfer?.setData('text/plain', group.key); if (event.dataTransfer) event.dataTransfer.effectAllowed = 'move'; chip.classList.add('dragging'); }); chip.addEventListener('dragend', finishLayoutDrag); slot.appendChild(chip); } else { const empty = document.createElement('span'); empty.className = 'layout-empty'; empty.textContent = t('Drop here', 'ここへドロップ'); slot.appendChild(empty); } slots.appendChild(slot); }); card.appendChild(slots); cards.appendChild(card); });
  const separate = document.createElement('div'); separate.className = 'layout-new'; separate.textContent = `＋ ${t('Drop here for a new graph', 'ここへドロップして新しいグラフ')}`; separate.addEventListener('dragover', (event) => { if (!draggedGroupKey) return; event.preventDefault(); separate.classList.add('drop-target'); }); separate.addEventListener('dragleave', () => separate.classList.remove('drop-target')); separate.addEventListener('drop', (event) => { event.preventDefault(); const key = layoutDragKey(event); if (!key) return; groupLayout = moveChartGroupToNewGraph(graphs.map((graph) => graph.map((group) => group.key)), key); finishLayoutDrag(); draw(); }); cards.appendChild(separate);
}
function enableLayoutDrop(slot: HTMLElement, graphIndex: number, axisIndex: 0 | 1): void { slot.addEventListener('dragover', (event) => { if (!draggedGroupKey) return; event.preventDefault(); slot.classList.add('drop-target'); }); slot.addEventListener('dragleave', () => slot.classList.remove('drop-target')); slot.addEventListener('drop', (event) => { event.preventDefault(); const key = layoutDragKey(event); if (!key) return; const layout = comparisonGraphs(comparisonGroups(comparisonEntries())).map((graph) => graph.map((group) => group.key)); groupLayout = moveChartGroup(layout, key, graphIndex, axisIndex); finishLayoutDrag(); draw(); }); }
function layoutDragKey(event: DragEvent): string | undefined { return draggedGroupKey ?? (event.dataTransfer?.getData('text/plain') || undefined); }
function finishLayoutDrag(): void { draggedGroupKey = undefined; app.querySelectorAll('.dragging,.drop-target').forEach((element) => element.classList.remove('dragging', 'drop-target')); }

function renderLegend(graphs: readonly ComparisonGraph[], width: number): readonly number[] {
  const host = app.querySelector<HTMLElement>('.legend')!; host.replaceChildren(); host.style.width = `${width}px`; const heights: number[] = []; let top = 18;
  graphs.forEach((graph, graphIndex) => { const row = document.createElement('div'); row.className = 'legend-group'; row.style.top = `${top}px`; const title = document.createElement('span'); title.className = 'legend-title'; title.textContent = `${t('Graph', 'グラフ')} ${graphIndex + 1}`; const items = document.createElement('div'); items.className = 'legend-items'; graph.forEach((group, axisIndex) => { for (const item of group.entries) { const entry = document.createElement('span'); entry.className = 'legend-entry'; const color = document.createElement('i'); color.style.borderTopColor = signalColor(item.series.definition.id); color.style.borderTopStyle = dashStyle(item.clipIndex); const axis = document.createElement('b'); axis.className = 'axis-badge'; axis.textContent = axisIndex === 0 ? 'L' : 'R'; const label = document.createElement('span'); label.className = 'legend-label'; label.textContent = `${item.clip.name} · ${comparisonLegendLabel(item.series.definition, group.displayUnit)}`; entry.append(color, axis, label); items.appendChild(entry); } }); row.append(title, items); host.appendChild(row); const height = Math.max(34, Math.ceil(row.scrollHeight) + 1); row.style.height = `${height}px`; heights.push(height); top += height + GRAPH_HEIGHT; }); return heights;
}
function signalColor(id: string): string { return colors.get(id) ?? SIGNAL_COLOR_PRESETS[0]; }
function dashStyle(index: number): string { return index % dashPatterns.length === 0 ? 'solid' : index % dashPatterns.length === 1 ? 'dashed' : 'dotted'; }

function draw(renderControls = true): void {
  const entries = comparisonEntries(); const groups = comparisonGroups(entries); const graphs = comparisonGraphs(groups); const graphCount = Math.max(1, graphs.length); const nextFull = availableRange(entries); fullRange = nextFull; viewRange = reconcileViewRange(viewRange, nextFull); updateZoomControls(); saveImageButton.disabled = !nextFull || !graphs.length; if (renderControls) renderLayoutEditor(); const wrap = canvas.parentElement!; const width = Math.max(320, wrap.clientWidth); if (renderControls || legendHeights.length !== graphCount) legendHeights = renderLegend(graphs, width); const height = 18 + graphCount * GRAPH_HEIGHT + legendHeights.reduce((sum, value) => sum + value, 0) + 34; const ratio = devicePixelRatio || 1; canvas.width = width * ratio; canvas.height = height * ratio; canvas.style.width = `${width}px`; canvas.style.height = `${height}px`; const context = canvas.getContext('2d')!; context.scale(ratio, ratio); context.clearRect(0, 0, width, height); context.fillStyle = css('--vscode-editor-background', '#1e1e1e'); context.fillRect(0, 0, width, height); hoverScale = undefined;
  if (!nextFull || !viewRange || !graphs.length) { context.fillStyle = css('--vscode-descriptionForeground', '#888'); context.fillText(selected.size ? t('No comparable samples for the selected Signals.', '選択したSignalに比較可能なサンプルがありません。') : t('Select Signals from the left pane.', '左側からSignalを選択してください。'), 20, 30); return; }
  hoverScale = { xMin: viewRange.start, xMax: viewRange.end, left: 92, width: Math.max(32, width - 184), graphCount: graphs.length }; paintChart(context, width, graphs, viewRange, legendHeights, 18, true);
}

function paintChart(context: CanvasRenderingContext2D, width: number, graphs: readonly ComparisonGraph[], range: TimeRange, graphLegendHeights: readonly number[], chartTop: number, interactive: boolean): void {
  const graphSignalIds = comparisonGraphSignalIds(graphs); const margin = { left: 92, right: 92 }; const plotW = Math.max(32, width - margin.left - margin.right); const xMin = range.start; const xMax = range.end === range.start ? range.start + 1 : range.end; const x = (value: number) => margin.left + (value - xMin) / (xMax - xMin) * plotW; context.font = '11px sans-serif'; context.lineWidth = 1; let precedingHeight = 0;
  graphs.forEach((graph, graphIndex) => {
    const legendHeight = graphLegendHeights[graphIndex] ?? 0; if (!interactive) paintGraphLegend(context, graph, graphIndex, width, chartTop + precedingHeight); const graphTop = chartTop + precedingHeight + legendHeight; precedingHeight += legendHeight + GRAPH_HEIGHT; const laneTop = graphTop + 30; const laneHeight = GRAPH_HEIGHT - 58; const hoverValues: CanvasHoverValue[] = []; const markerValues = new Map<string, CanvasHoverValue[]>(); context.strokeStyle = css('--vscode-panel-border', '#777'); context.strokeRect(margin.left, laneTop, plotW, laneHeight);
    for (let tick = 0; tick <= 5; tick++) { const value = xMin + (xMax - xMin) * tick / 5; const label = `${format(value)}s`; const px = x(value); context.globalAlpha = .48; context.beginPath(); context.moveTo(px, laneTop); context.lineTo(px, laneTop + laneHeight); context.stroke(); context.globalAlpha = 1; context.fillStyle = css('--vscode-descriptionForeground', '#888'); context.fillText(label, Math.max(margin.left, Math.min(width - margin.right - context.measureText(label).width, px - context.measureText(label).width / 2)), laneTop + laneHeight + 20); }
    graph.forEach((group, axisIndex) => {
      const rawRange = comparisonGroupRange(group, range); let yMin = rawRange.minimum; let yMax = rawRange.maximum; if (yMin === yMax) { const pad = Math.abs(yMin) * .05 || 1; yMin -= pad; yMax += pad; } const y = (value: number) => laneTop + (1 - (value - yMin) / (yMax - yMin)) * laneHeight; const rightAxis = axisIndex === 1; context.save(); context.font = '600 11px sans-serif'; context.textAlign = rightAxis ? 'right' : 'left'; context.fillStyle = css('--vscode-foreground', '#ddd'); context.fillText(ellipsize(context, group.label, Math.max(24, plotW / 2 - 12)), rightAxis ? margin.left + plotW : margin.left, graphTop + 16); context.restore();
      for (let tick = 0; tick <= 4; tick++) { const value = yMax - (yMax - yMin) * tick / 4; const py = y(value); if (axisIndex === 0) { context.strokeStyle = css('--vscode-panel-border', '#777'); context.globalAlpha = .55; context.beginPath(); context.moveTo(margin.left, py); context.lineTo(margin.left + plotW, py); context.stroke(); context.globalAlpha = 1; } const label = format(value); context.fillStyle = css('--vscode-descriptionForeground', '#888'); context.fillText(label, rightAxis ? margin.left + plotW + 7 : Math.max(4, margin.left - context.measureText(label).width - 7), Math.min(laneTop + laneHeight - 2, py + 4)); }
      for (const entry of group.entries) { context.save(); context.beginPath(); context.rect(margin.left, laneTop, plotW, laneHeight); context.clip(); context.setLineDash(dashPatterns[entry.clipIndex % dashPatterns.length]); context.strokeStyle = signalColor(entry.series.definition.id); context.beginPath(); let started = false; let previousTimestamp: number | undefined; for (const sample of entry.series.samples) { const value = comparisonValue(entry.series, sample.value, group.displayUnit); const usable = Number.isFinite(value) && (sample.quality === undefined || sample.quality === 'valid'); if (!usable) { if (!connectGaps) started = false; continue; } const separated = !connectGaps && previousTimestamp !== undefined && crossesSeriesGap(entry.series.gaps, previousTimestamp, sample.timestamp); const px = x(sample.timestamp - entry.clip.anchorTimestamp); const py = y(value); started && !separated ? context.lineTo(px, py) : context.moveTo(px, py); started = true; previousTimestamp = sample.timestamp; } context.stroke(); context.restore(); }
      if (interactive && hoverRelativeTimestamp !== undefined && hoverGraphIndex === graphIndex) for (const entry of group.entries) { const rawValue = renderedSeriesValueAt(entry.series, entry.clip.anchorTimestamp + hoverRelativeTimestamp, connectGaps); if (rawValue === undefined) continue; const value = comparisonValue(entry.series, rawValue, group.displayUnit); const py = y(value); if (Number.isFinite(py) && py >= laneTop && py <= laneTop + laneHeight) hoverValues.push({ y: py, text: displayValueLabel(value, group.displayUnit), color: signalColor(entry.series.definition.id) }); }
      for (const marker of markers.values()) { if (findGraphIndexBySignals(graphSignalIds, marker.signalIds) !== graphIndex || marker.relativeTimestamp < xMin || marker.relativeTimestamp > xMax) continue; for (const entry of group.entries) { const rawValue = renderedSeriesValueAt(entry.series, entry.clip.anchorTimestamp + marker.relativeTimestamp, connectGaps); if (rawValue === undefined) continue; const value = comparisonValue(entry.series, rawValue, group.displayUnit); const py = y(value); if (!Number.isFinite(py) || py < laneTop || py > laneTop + laneHeight) continue; const values = markerValues.get(marker.id) ?? []; values.push({ y: py, text: displayValueLabel(value, group.displayUnit), color: signalColor(entry.series.definition.id) }); markerValues.set(marker.id, values); } }
    });
    context.setLineDash([]); const visibleMarkers = [...markers.values()].filter((marker) => findGraphIndexBySignals(graphSignalIds, marker.signalIds) === graphIndex && marker.relativeTimestamp >= xMin && marker.relativeTimestamp <= xMax); for (const marker of visibleMarkers) { const cursorX = x(marker.relativeTimestamp); context.strokeStyle = css('--vscode-focusBorder', '#007acc'); context.beginPath(); context.moveTo(cursorX, laneTop); context.lineTo(cursorX, laneTop + laneHeight); context.stroke(); } if (interactive && hoverRelativeTimestamp !== undefined && hoverGraphIndex === graphIndex) { const cursorX = x(hoverRelativeTimestamp); context.strokeStyle = css('--vscode-editorCursor-foreground', '#fff'); context.beginPath(); context.moveTo(cursorX, laneTop); context.lineTo(cursorX, laneTop + laneHeight); context.stroke(); }
    const occupiedLabels: HoverLabelRect[] = []; const fixedTimestampMarkers = visibleMarkers.map((marker) => { const timestampMarker = createTimestampMarker(context, x(marker.relativeTimestamp), `${marker.relativeTimestamp >= 0 ? '+' : ''}${format(marker.relativeTimestamp)} s`, margin.left, margin.left + plotW, laneTop + laneHeight, occupiedLabels, laneTop); occupiedLabels.push(timestampMarker.rect); return timestampMarker; }); const timestampMarker = interactive && hoverRelativeTimestamp !== undefined && hoverGraphIndex === graphIndex ? createTimestampMarker(context, x(hoverRelativeTimestamp), `${hoverRelativeTimestamp >= 0 ? '+' : ''}${format(hoverRelativeTimestamp)} s`, margin.left, margin.left + plotW, laneTop + laneHeight, occupiedLabels, laneTop) : undefined; if (timestampMarker) occupiedLabels.push(timestampMarker.rect); for (const marker of visibleMarkers) paintHoverValues(context, x(marker.relativeTimestamp), markerValues.get(marker.id) ?? [], margin.left, margin.left + plotW, laneTop, laneTop + laneHeight, occupiedLabels); if (timestampMarker && hoverRelativeTimestamp !== undefined) paintHoverValues(context, x(hoverRelativeTimestamp), hoverValues, margin.left, margin.left + plotW, laneTop, laneTop + laneHeight, occupiedLabels); for (const fixedTimestampMarker of fixedTimestampMarkers) paintTimestampMarker(context, fixedTimestampMarker); if (timestampMarker) paintTimestampMarker(context, timestampMarker);
  }); context.setLineDash([]);
}

function hover(event: MouseEvent): void { const position = positionAt(event); if (!position) { clearHover(); return; } hoverRelativeTimestamp = position.relativeTimestamp; hoverGraphIndex = position.graphIndex; scheduleInteractionDraw(); }
function addMarker(event: MouseEvent): void { const position = positionAt(event); if (!position) return; const signalIds = comparisonGraphSignalIds(comparisonGraphs(comparisonGroups(comparisonEntries())))[position.graphIndex]; if (!signalIds?.length) return; const id = `marker-${++markerCounter}`; markers.set(id, { id, relativeTimestamp: position.relativeTimestamp, signalIds }); clearHover(false); updateMarkerControls(); draw(false); }
function positionAt(event: MouseEvent): { readonly relativeTimestamp: number; readonly graphIndex: number } | undefined { if (!hoverScale || !selected.size || !visibleClips.size) return undefined; const rect = canvas.getBoundingClientRect(); const position = event.clientX - rect.left; const graphY = event.clientY - rect.top - 18; const graphIndex = graphIndexAtOffset(graphY, legendHeights); if (position < hoverScale.left || position > hoverScale.left + hoverScale.width || graphIndex === undefined || graphIndex >= hoverScale.graphCount) return undefined; const fraction = (position - hoverScale.left) / hoverScale.width; return { relativeTimestamp: hoverScale.xMin + fraction * (hoverScale.xMax - hoverScale.xMin), graphIndex }; }

function zoom(factor: number, center?: number): void { if (!fullRange || !viewRange) return; const fullSpan = fullRange.end - fullRange.start || 1; const currentSpan = viewRange.end - viewRange.start || fullSpan; const span = Math.max(fullSpan * .005, Math.min(fullSpan, currentSpan * factor)); const pivot = center ?? (viewRange.start + viewRange.end) / 2; const ratio = (pivot - viewRange.start) / currentSpan; let start = pivot - span * ratio; let end = start + span; if (start < fullRange.start) { start = fullRange.start; end = start + span; } if (end > fullRange.end) { end = fullRange.end; start = end - span; } viewRange = { start, end }; clearHover(false); draw(); }
function pan(direction: -1 | 1): void { if (!fullRange || !viewRange) return; const fullSpan = fullRange.end - fullRange.start; const span = viewRange.end - viewRange.start; if (span >= fullSpan - 1e-12) return; const shift = span * .18 * direction; let start = viewRange.start + shift; let end = viewRange.end + shift; if (start < fullRange.start) { start = fullRange.start; end = start + span; } if (end > fullRange.end) { end = fullRange.end; start = end - span; } viewRange = { start, end }; clearHover(false); draw(); }
function handleWheel(event: WheelEvent): void { if (!fullRange || !viewRange) return; const gesture = chartWheelGesture(event, canvas.clientWidth); if (gesture.kind === 'scroll' || !gesture.delta) return; event.preventDefault(); if (viewportTimer !== undefined) window.clearTimeout(viewportTimer); const center = gesture.kind === 'zoom' ? positionAt(event as unknown as MouseEvent)?.relativeTimestamp : undefined; viewportTimer = window.setTimeout(() => { viewportTimer = undefined; if (gesture.kind === 'zoom') zoom(gesture.delta < 0 ? 1 / 1.5 : 1.5, center); else pan(Math.sign(gesture.delta) < 0 ? -1 : 1); }, 70); }
function updateZoomControls(): void { const zoomed = Boolean(fullRange && viewRange && (Math.abs(viewRange.start - fullRange.start) > 1e-9 || Math.abs(viewRange.end - fullRange.end) > 1e-9)); app.querySelector<HTMLButtonElement>('.zoom-reset')!.disabled = !zoomed; app.querySelector<HTMLButtonElement>('.zoom-out')!.disabled = !zoomed; app.querySelector<HTMLButtonElement>('.zoom-in')!.disabled = !fullRange || !viewRange || (viewRange.end - viewRange.start) <= (fullRange.end - fullRange.start) * .005 + 1e-12; app.querySelector<HTMLButtonElement>('.pan-left')!.disabled = !zoomed || !fullRange || !viewRange || viewRange.start <= fullRange.start + 1e-12; app.querySelector<HTMLButtonElement>('.pan-right')!.disabled = !zoomed || !fullRange || !viewRange || viewRange.end >= fullRange.end - 1e-12; app.querySelector('.view-range')!.textContent = viewRange ? `${format(viewRange.start)}–${format(viewRange.end)} s · ${format(viewRange.end - viewRange.start)} s` : ''; }

function saveImage(): void { const graphs = comparisonGraphs(comparisonGroups(comparisonEntries())); if (!viewRange || !graphs.length || saveImageButton.disabled) return; const width = 1600; const exportCanvas = document.createElement('canvas'); exportCanvas.width = width; let context = exportCanvas.getContext('2d'); if (!context) return; const heights = graphs.map((graph) => measureGraphLegendHeight(context!, graph, width)); const contentHeight = graphs.length * GRAPH_HEIGHT + heights.reduce((sum, value) => sum + value, 0); exportCanvas.height = Math.max(900, 92 + contentHeight); context = exportCanvas.getContext('2d'); if (!context) return; context.fillStyle = css('--vscode-editor-background', '#1e1e1e'); context.fillRect(0, 0, width, exportCanvas.height); context.fillStyle = css('--vscode-foreground', '#ddd'); context.font = '600 22px sans-serif'; context.fillText('SigMixa · Clip Comparison', 24, 34); context.font = '12px sans-serif'; const label = `${format(viewRange.start)}–${format(viewRange.end)} s`; context.fillStyle = css('--vscode-descriptionForeground', '#999'); context.fillText(label, width - context.measureText(label).width - 24, 32); paintChart(context, width, graphs, viewRange, heights, 58, false); vscode.postMessage({ type: 'saveClipComparisonImage', dataUrl: exportCanvas.toDataURL('image/png') }); }
function paintGraphLegend(context: CanvasRenderingContext2D, graph: ComparisonGraph, graphIndex: number, width: number, top: number): void { context.save(); context.font = '600 12px sans-serif'; context.fillStyle = css('--vscode-descriptionForeground', '#999'); context.fillText(`${t('Graph', 'グラフ')} ${graphIndex + 1}`, 24, top + 20); let x = 94; let y = top + 20; context.font = '12px sans-serif'; graph.forEach((group, axisIndex) => { for (const item of group.entries) { const label = `${axisIndex === 0 ? 'L' : 'R'} · ${item.clip.name} · ${comparisonLegendLabel(item.series.definition, group.displayUnit)}`; const entryWidth = 30 + context.measureText(label).width; if (x + entryWidth > width - 24) { x = 94; y += 20; } context.setLineDash(dashPatterns[item.clipIndex % dashPatterns.length]); context.strokeStyle = signalColor(item.series.definition.id); context.lineWidth = 3; context.beginPath(); context.moveTo(x, y - 4); context.lineTo(x + 16, y - 4); context.stroke(); context.setLineDash([]); context.fillStyle = css('--vscode-foreground', '#ddd'); context.fillText(ellipsize(context, label, width - x - 28), x + 22, y); x += Math.min(entryWidth, width - x - 24) + 16; } }); context.restore(); }
function measureGraphLegendHeight(context: CanvasRenderingContext2D, graph: ComparisonGraph, width: number): number { context.save(); context.font = '12px sans-serif'; let x = 94; let rows = 1; graph.forEach((group, axisIndex) => { for (const item of group.entries) { const label = `${axisIndex === 0 ? 'L' : 'R'} · ${item.clip.name} · ${comparisonLegendLabel(item.series.definition, group.displayUnit)}`; const entryWidth = 30 + context.measureText(label).width; if (x + entryWidth > width - 24) { x = 94; rows++; } x += Math.min(entryWidth, width - x - 24) + 16; } }); context.restore(); return Math.max(34, 12 + rows * 20); }

function clearHover(redraw = true): void { hoverRelativeTimestamp = undefined; hoverGraphIndex = undefined; if (redraw) scheduleInteractionDraw(); }
function scheduleInteractionDraw(): void { if (interactionDrawScheduled) return; interactionDrawScheduled = true; requestAnimationFrame(() => { interactionDrawScheduled = false; draw(false); }); }
function paintHoverValues(context: CanvasRenderingContext2D, cursorX: number, values: readonly CanvasHoverValue[], left: number, right: number, top: number, bottom: number, occupied: HoverLabelRect[] = []): void { context.save(); context.font = `600 11px ${css('--vscode-editor-font-family', 'monospace')}`; context.textBaseline = 'middle'; const positioned = layoutHoverLabelBoxes(values.map((value) => ({ ...value, cursorX, width: context.measureText(value.text).width + 10, height: 16 })), { left, right, top, bottom }, occupied); for (const value of positioned) { context.strokeStyle = value.color; context.globalAlpha = .7; context.beginPath(); context.arc(cursorX, value.y, 3, 0, Math.PI * 2); context.fillStyle = value.color; context.fill(); context.moveTo(cursorX, value.y); context.lineTo(value.placeLeft ? value.boxX + value.width : value.boxX, value.labelY); context.stroke(); context.globalAlpha = .92; context.fillStyle = css('--vscode-editorHoverWidget-background', '#252526'); context.fillRect(value.boxX, value.boxY, value.width, value.height); context.globalAlpha = 1; context.strokeStyle = value.color; context.strokeRect(value.boxX, value.boxY, value.width, value.height); context.fillStyle = value.color; context.fillText(value.text, value.boxX + 5, value.labelY); } occupied.push(...positioned.map((value) => value.rect)); context.restore(); }
function createTimestampMarker(context: CanvasRenderingContext2D, cursorX: number, text: string, left: number, right: number, bottom: number, occupied: readonly HoverLabelRect[] = [], top = 0): CanvasTimestampMarker { context.save(); context.font = `600 11px ${css('--vscode-editor-font-family', 'monospace')}`; const width = context.measureText(text).width + 12; context.restore(); return { text, rect: layoutTimestampMarker(cursorX, width, 18, left, right, bottom, occupied, top) }; }
function paintTimestampMarker(context: CanvasRenderingContext2D, marker: CanvasTimestampMarker): void { context.save(); context.font = `600 11px ${css('--vscode-editor-font-family', 'monospace')}`; context.textAlign = 'center'; context.textBaseline = 'middle'; context.fillStyle = css('--vscode-editorHoverWidget-background', '#252526'); context.fillRect(marker.rect.x, marker.rect.y, marker.rect.width, marker.rect.height); context.strokeStyle = css('--vscode-editorCursor-foreground', '#fff'); context.strokeRect(marker.rect.x, marker.rect.y, marker.rect.width, marker.rect.height); context.fillStyle = css('--vscode-editor-foreground', '#ddd'); context.fillText(marker.text, marker.rect.x + marker.rect.width / 2, marker.rect.y + marker.rect.height / 2); context.restore(); }
function updateMarkerControls(): void { markerClear.disabled = markers.size === 0; }

function availableRange(entries: readonly ComparisonEntry[]): TimeRange | undefined { let start = Infinity; let end = -Infinity; for (const entry of entries) for (const sample of entry.series.samples) { if (!Number.isFinite(sample.value)) continue; const relative = sample.timestamp - entry.clip.anchorTimestamp; start = Math.min(start, relative); end = Math.max(end, relative); } if (!Number.isFinite(start) || !Number.isFinite(end)) return undefined; return { start, end: end === start ? start + 1 : end }; }
function reconcileViewRange(view: TimeRange | undefined, full: TimeRange | undefined): TimeRange | undefined { if (!full || !view) return full; const fullSpan = full.end - full.start; const span = Math.min(fullSpan, Math.max(0, view.end - view.start)); if (span >= fullSpan || view.end < full.start || view.start > full.end) return full; const start = Math.max(full.start, Math.min(view.start, full.end - span)); return { start, end: start + span }; }
function comparisonGroupRange(group: ComparisonGroup, visible: TimeRange): { minimum: number; maximum: number } { if (normalized) return { minimum: 0, maximum: 100 }; if (axisRange.mode === 'global') return displaySeriesRange(group.entries.map((entry) => entry.series), axisRange, undefined, group.displayUnit); let minimum = Infinity; let maximum = -Infinity; for (const entry of group.entries) for (const sample of entry.series.samples) { const relative = sample.timestamp - entry.clip.anchorTimestamp; if (relative < visible.start || relative > visible.end || (sample.quality !== undefined && sample.quality !== 'valid')) continue; const value = comparisonValue(entry.series, sample.value, group.displayUnit); if (!Number.isFinite(value)) continue; minimum = Math.min(minimum, value); maximum = Math.max(maximum, value); } if (!Number.isFinite(minimum) || !Number.isFinite(maximum)) return displaySeriesRange(group.entries.map((entry) => entry.series), axisRange, undefined, group.displayUnit); if (axisRange.includeZero) { minimum = Math.min(0, minimum); maximum = Math.max(0, maximum); } return { minimum, maximum }; }
function comparisonEntries(): readonly ComparisonEntry[] { const active = clips.filter((clip) => visibleClips.has(clip.id)); return active.flatMap((clip) => clip.series.map((series) => ({ clip, clipIndex: clips.findIndex((item) => item.id === clip.id), series }))); }
function comparisonGroups(entries: readonly ComparisonEntry[]): readonly ComparisonGroup[] { return normalized ? entries.length ? [{ key: 'normalized', label: '0–100%', entries }] : [] : groupComparisonSeries(entries); }
function comparisonGraphSignalIds(graphs: readonly ComparisonGraph[]): readonly string[][] { return graphs.map((graph) => [...new Set(graph.flatMap((group) => group.entries.map((entry) => entry.series.definition.id)))]); }
function graphIndexAtOffset(offset: number, heights: readonly number[]): number | undefined { if (offset < 0) return undefined; let top = 0; for (let index = 0; index < heights.length; index++) { const legendBottom = top + heights[index]; if (offset < legendBottom) return undefined; const graphBottom = legendBottom + GRAPH_HEIGHT; if (offset < graphBottom) return index; top = graphBottom; } return undefined; }
function groupComparisonSeries(entries: readonly ComparisonEntry[]): readonly ComparisonGroup[] { const groups = new Map<string, { key: string; order: number; entries: ComparisonEntry[] }>(); for (const entry of entries) { const unit = entry.series.definition.unit?.trim(); const conversion = resolveDisplayUnit(unit); const key = conversion ? `family:${conversion.family}` : unit ? `unit:${unit.toLowerCase()}` : 'empty'; const group = groups.get(key) ?? { key, order: conversion?.order ?? (unit ? 10_000 : 20_000), entries: [] }; group.entries.push(entry); groups.set(key, group); } return [...groups.values()].map((group) => { const displayUnit = preferredDisplayUnit(group.entries.map((entry) => entry.series.definition.unit)); return { ...group, displayUnit, label: displayUnit ?? t('(no unit)', '(単位なし)') }; }).sort((left, right) => left.order - right.order || left.label.localeCompare(right.label)); }
function comparisonValue(series: ComparisonEntry['series'], value: number, displayUnit?: string): number { return normalized ? normalizeValue(value, series.globalMinimum ?? value, series.globalMaximum ?? value) : convertDisplayUnit(value, series.definition.unit, displayUnit); }
function displayValueLabel(value: number, displayUnit?: string): string { const unit = normalized ? '%' : displayUnit?.trim(); return `${format(value)}${unit ? ` ${unit}` : ''}`; }
function comparisonLegendLabel(definition: ComparisonEntry['series']['definition'], displayUnit?: string): string { const sourceUnit = definition.unit?.trim(); const unit = !normalized && displayUnit && sourceUnit && displayUnit !== sourceUnit ? `${sourceUnit} → ${displayUnit}` : sourceUnit; return `${definition.name}${unit ? ` (${unit})` : ''}`; }
function css(name: string, fallback: string): string { return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || fallback; }
function format(value: number): string { return Number(value.toPrecision(7)).toString(); }
function ellipsize(context: CanvasRenderingContext2D, text: string, maxWidth: number): string { if (context.measureText(text).width <= maxWidth) return text; let low = 0; let high = text.length; while (low < high) { const middle = Math.ceil((low + high) / 2); if (context.measureText(`${text.slice(0, middle)}…`).width <= maxWidth) low = middle; else high = middle - 1; } return `${text.slice(0, low)}…`; }

window.addEventListener('message', (event: MessageEvent<ClipComparisonToWebview>) => { const message = event.data; if (message.type === 'init') { clips = message.clips.map((clip) => ({ ...clip })); visibleClips.clear(); clips.forEach((clip) => visibleClips.add(clip.id)); selected.clear(); message.selectedSignalIds.forEach((id) => selected.add(id)); colors.clear(); message.definitions.forEach((definition, index) => colors.set(definition.id, SIGNAL_COLOR_PRESETS[index % SIGNAL_COLOR_PRESETS.length])); selector.setCatalog(message.definitions, message.groups); updateSelectionStatus(); renderClips(); updateModeButtons(); draw(); } else if (message.type === 'seriesChanged' && message.requestId === latestSeriesRequest) { const next = new Map(message.seriesByClip.map((item) => [item.clipId, item.series])); clips = clips.map((clip) => ({ ...clip, series: next.get(clip.id) ?? [] })); updateSelectionStatus(); draw(); } else if (message.type === 'anchorChanged') { clips = clips.map((clip) => clip.id === message.clipId ? { ...clip, anchorTimestamp: message.anchorTimestamp } : clip); clearHover(false); renderClips(); draw(); } });

vscode.postMessage({ type: 'ready' });
